"""
hierarchical_supcon.py — Hierarchical Supervised Contrastive Loss

Positive pair weighting based on CWE tree distance (when matrix provided):

  With intragroup_only=True (default — recommended):
    Distance matrix is used ONLY for within-group positive pairs (same group_id,
    different CWE). Cross-group pairs are always 0.0 (negatives), regardless of
    their tree distance. This is correct because CWE groups are anchored at
    different depths in the CWE tree, making cross-group distances non-comparable.
    Using cross-group matrix distances dilutes the contrastive signal with noisy
    weak positives (observed: v2 with matrix < v1 alpha-only on all metrics).

    - Same CWE (both > 0)              → weight 1.0
    - Same group, both in matrix       → weight_fn(norm_dist(i, j))
    - Same group, one/both not in mat  → weight alpha (fallback)
    - Different group / benign         → weight 0.0 (always, even if in matrix)

  With intragroup_only=False (legacy behavior):
    Matrix weights are applied to ALL pairs where both CWEs are in the matrix,
    including cross-group pairs. This produced worse results due to depth-
    asymmetric group anchors polluting cross-group pair weights.

Without matrix (alpha-only fallback):
  - Same CWE                       → weight 1.0
  - Same group, different CWE      → weight alpha
  - Different group / benign       → weight 0.0

weight_fn options (applied to normalised distance d ∈ [0, 1]):
  "linear" : w = 1 - d                       (default)
  "exp"    : w = exp(-exp_scale * d)          (sharper decay)
  "power"  : w = (1 - d) ** power            (tunable curve)

Benign samples (y == 0) are excluded from the anchor set but still serve as
negatives in the denominator, pushing vulnerable embeddings away from benign.

Loss for anchor i:
    L_i = -1/|P_i| * sum_{j in P_i} w_ij * log [ exp(z_i·z_j / tau) /
                                                   sum_{k != i} exp(z_i·z_k / tau) ]
"""

from __future__ import annotations

import json
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F


class HierarchicalSupConLoss(nn.Module):
    """
    Parameters
    ----------
    temperature : float
        Softmax temperature (default 0.07).
    alpha : float
        Fallback weight for same-group, different-CWE pairs when the distance
        matrix is unavailable or a CWE is not in the matrix (default 0.5).
        Hard positive (same CWE) weight is always 1.0.
    dist_matrix_path : str | Path | None
        Path to cwe_distance_matrix.json generated by analyze_cwe_tree.py.
        When provided with cwe_vocab, enables continuous tree-distance weights
        instead of the binary alpha fallback.
    cwe_vocab : dict[str, int] | None
        Mapping from CWE string e.g. "CWE-119" to vocab index used in the
        dataset labels. Required to resolve matrix row/col indices from labels.
    weight_fn : str
        How to convert normalised distance d ∈ [0,1] to pair weight:
        "linear" (default) : w = 1 - d
        "exp"              : w = exp(-exp_scale * d)
        "power"            : w = (1 - d) ** power
    exp_scale : float
        Decay rate for weight_fn="exp" (default 5.0).
        Higher → sharper falloff; at d=1 weight → exp(-exp_scale).
    power : float
        Exponent for weight_fn="power" (default 2.0).
        >1 → concave (penalises moderate distance); <1 → convex.
    min_weight : float
        Floor applied to all matrix-derived weights before using them
        (default 0.0). Set > 0 to keep a weak positive signal for all
        in-matrix pairs regardless of distance.
    intragroup_only : bool
        When True (default), matrix-derived weights are restricted to within-group
        positive pairs only. Cross-group pairs are zeroed even if both CWEs are in
        the distance matrix. Recommended: CWE groups are anchored at different tree
        depths, making cross-group distances non-comparable and the weighting noisy.
        Set False to restore the legacy behavior (matrix weights for all pairs).
    """

    def __init__(
        self,
        temperature: float = 0.07,
        alpha: float = 0.5,
        dist_matrix_path: str | Path | None = None,
        cwe_vocab: dict[str, int] | None = None,
        weight_fn: str = "linear",
        exp_scale: float = 5.0,
        power: float = 2.0,
        min_weight: float = 0.0,
        intragroup_only: bool = True,
    ) -> None:
        super().__init__()
        self.temperature = temperature
        self.alpha = alpha
        self.weight_fn = weight_fn
        self.exp_scale = exp_scale
        self.power = power
        self.min_weight = min_weight
        self.intragroup_only = intragroup_only
        self._has_matrix = False

        if dist_matrix_path is not None and cwe_vocab is not None:
            p = Path(dist_matrix_path)
            if p.exists():
                with open(p, encoding="utf-8") as f:
                    data = json.load(f)

                cwe_order = data["cwe_order"]   # list[str], e.g. ["119", "125", …]
                matrix = torch.tensor(data["distance_matrix"], dtype=torch.float32)  # [M, M]

                # Build lookup: vocab_idx → matrix_row_idx (-1 if not in matrix).
                # cwe_vocab keys are like "CWE-119"; cwe_order entries are like "119".
                max_vocab_idx = max(cwe_vocab.values()) + 1 if cwe_vocab else 1
                lookup = torch.full((max_vocab_idx,), -1, dtype=torch.long)
                n_mapped = 0
                for mat_idx, cwe_num in enumerate(cwe_order):
                    cwe_str = f"CWE-{cwe_num}"
                    if cwe_str in cwe_vocab:
                        vocab_idx = cwe_vocab[cwe_str]
                        lookup[vocab_idx] = mat_idx
                        n_mapped += 1

                self.register_buffer("_dist_matrix", matrix)   # [M, M] normalised 0→1
                self.register_buffer("_vocab_to_mat", lookup)  # [V] vocab_idx → mat_idx

                self._has_matrix = True
                print(
                    f"[HierarchicalSupConLoss] Matrix loaded: {matrix.shape[0]} CWEs, "
                    f"{n_mapped}/{len(cwe_vocab)} vocab entries mapped to matrix."
                )
            else:
                print(
                    f"[HierarchicalSupConLoss] Warning: matrix not found at {p}. "
                    "Falling back to alpha group-based weighting."
                )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _continuous_weights(
        self,
        cwe_vocab_ids: torch.Tensor,  # [B]  raw CWE vocab indices (-1 for benign)
        vuln_mask: torch.Tensor,      # [B]  bool
        anc_idx: torch.Tensor,        # [A]  anchor positions in [B]
        n_vuln: int,
        B: int,
        device: torch.device,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Returns
        -------
        weights   : [A, B]  continuous positive weights from distance matrix.
        in_matrix : [A, B]  True where both CWEs were resolved in the matrix.
        """
        # Map vocab ids to matrix indices; clamp to valid range first.
        clamped = cwe_vocab_ids.clamp(min=0, max=self._vocab_to_mat.size(0) - 1)
        mat_ids = self._vocab_to_mat[clamped]   # [B]
        mat_ids[~vuln_mask] = -1                # benign → -1 (not in matrix)

        anc_mat = mat_ids[anc_idx]                           # [A]
        smp_mat = mat_ids.unsqueeze(0).expand(n_vuln, -1)   # [A, B]

        # Pairs where both anchor and sample are in the matrix
        in_matrix = (anc_mat.unsqueeze(1) >= 0) & (smp_mat >= 0)  # [A, B]

        weights = torch.zeros(n_vuln, B, device=device)

        if in_matrix.any():
            M = self._dist_matrix.size(0)
            ai_safe = anc_mat.clamp(min=0).unsqueeze(1).expand_as(smp_mat)  # [A, B]
            si_safe = smp_mat.clamp(min=0)                                   # [A, B]

            flat_idx = ai_safe.reshape(-1) * M + si_safe.reshape(-1)
            dists = self._dist_matrix.reshape(-1)[flat_idx].reshape(n_vuln, B)  # [A, B]

            # Convert normalised distance → weight via configured weight_fn.
            if self.weight_fn == "exp":
                continuous = torch.exp(-self.exp_scale * dists)
            elif self.weight_fn == "power":
                continuous = (1.0 - dists).clamp(min=0.0) ** self.power
            else:  # "linear" (default)
                continuous = (1.0 - dists).clamp(min=0.0)
            if self.min_weight > 0.0:
                continuous = continuous.clamp(min=self.min_weight)
            weights[in_matrix] = continuous[in_matrix]

        return weights, in_matrix

    # ------------------------------------------------------------------
    # Forward
    # ------------------------------------------------------------------

    def forward(
        self,
        z: torch.Tensor,
        labels: torch.Tensor,
        group_ids: torch.Tensor,
        cwe_vocab_ids: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """
        Parameters
        ----------
        z             : [B, D]  embeddings (Z_combined before classification heads)
        labels        : [B]     fine-grained class IDs (0 = benign)
        group_ids     : [B]     coarse group IDs (0 = benign group)
        cwe_vocab_ids : [B]     raw CWE vocab index from data.cwe_id (-1 for benign).
                                Enables distance-matrix weighting; if None, falls back
                                to binary group-based alpha weighting.

        Returns
        -------
        Scalar contrastive loss.
        """
        device = z.device

        # Only vulnerable samples participate as anchors
        vuln_mask = labels > 0
        n_vuln = int(vuln_mask.sum().item())
        if n_vuln < 2:
            return torch.tensor(0.0, device=device)

        # L2-normalise ALL embeddings
        z_norm = F.normalize(z, dim=-1)   # [B, D]
        B = z.size(0)

        z_anc = z_norm[vuln_mask]         # [A, D]
        l_anc = labels[vuln_mask]         # [A]
        g_anc = group_ids[vuln_mask]      # [A]

        # Cosine similarity: anchors × all [A, B]
        sim = torch.matmul(z_anc, z_norm.T) / self.temperature

        # Anchor positions in full batch
        anc_idx = torch.where(vuln_mask)[0]   # [A]

        # Self-pair mask [A, B]
        self_mask = torch.zeros(n_vuln, B, dtype=torch.bool, device=device)
        self_mask[torch.arange(n_vuln, device=device), anc_idx] = True

        # ── Build weight matrix ────────────────────────────────────────────────
        l_all = labels.unsqueeze(0)        # [1, B]
        g_all = group_ids.unsqueeze(0)     # [1, B]
        l_anc_e = l_anc.unsqueeze(1)       # [A, 1]
        g_anc_e = g_anc.unsqueeze(1)       # [A, 1]
        vuln_all = l_all > 0               # [1, B]

        same_cwe   = (l_anc_e == l_all) & vuln_all & ~self_mask          # [A, B]
        same_group = (g_anc_e == g_all) & ~same_cwe & vuln_all & ~self_mask  # [A, B]

        if self._has_matrix and cwe_vocab_ids is not None:
            # --- Continuous tree-distance weights ---
            weights, in_matrix = self._continuous_weights(
                cwe_vocab_ids, vuln_mask, anc_idx, n_vuln, B, device
            )
            # Same-CWE pairs: force weight 1.0
            weights[same_cwe] = 1.0

            if self.intragroup_only:
                # Cross-group pairs must be 0 — CWE groups sit at different depths
                # in the CWE tree, so inter-group tree distances are not comparable.
                # Zero out any matrix weight that leaked through to cross-group pairs.
                cross_group = ~(same_group | same_cwe | self_mask)
                weights[cross_group] = 0.0

            # Within-group pairs not in matrix → alpha fallback
            fallback = same_group & ~in_matrix
            weights[fallback] = self.alpha

            weights[self_mask] = 0.0

        else:
            # --- Binary alpha fallback (original behaviour) ---
            weights = torch.zeros(n_vuln, B, device=device)
            weights[same_cwe]   = 1.0
            weights[same_group] = self.alpha

        # ── Contrastive loss ──────────────────────────────────────────────────
        has_pos = (weights > 0).any(dim=1)   # [A]
        if not has_pos.any():
            return torch.tensor(0.0, device=device)

        # Numerical stability
        sim_stable = sim - sim.detach().amax(dim=1, keepdim=True)
        exp_all = torch.exp(sim_stable)
        exp_all = exp_all.masked_fill(self_mask, 0.0)

        log_denom = torch.log(exp_all.sum(dim=1, keepdim=True).clamp(min=1e-8))
        log_prob  = sim_stable - log_denom                      # [A, B]

        n_pos = weights.sum(dim=1).clamp(min=1e-8)             # [A]
        per_anchor = -(weights * log_prob).sum(dim=1) / n_pos  # [A]

        return per_anchor[has_pos].mean()
