"""
gen_continual_arch_configs.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Generate the continual-learning (domain-IL + CIL) configs for the hybrid (O1)
and sequential (S1) architectures from the graph (N48) templates.

The continual protocol is identical across architectures. Only two things change
per arch, exactly as in classification:
  1. the `model:` block  — swapped for the arch's nine classification model block
     (O1 = live-LM hibrida ml5120, S1 = lmgat_seqgnn ml1024, same as graph).
  2. the `train:` block   — swapped too (hybrid fine-tunes the LM → lm_lr + amp).
Everything else (data source, ewc, replay) is copied from the N48 template, with
num_classes carried over per template (26 domain, 36 CIL) and the ewc checkpoint
dir renamed n48_taskA -> {o1,s1}_taskA so the three archs never collide on a pod.

Seq reuses the graph datasets (ml1024, live_lm none). Hybrid needs ml5120 (its
model block sets func_max_length: 5120, so the loader targets the ml5120 .pt).

Run: PYTHONPATH=src python scripts/gen_continual_arch_configs.py
"""
from __future__ import annotations
import copy
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / "configs" / "ablation" / "relearn"
CIL = CFG / "cil"

# arch -> (nine classification config providing the model+train block, taskA ckpt dir)
ARCHS = {
    "O1": {"cls": ROOT / "configs" / "ablation" / "phase13" / "O1_unixcoder_nine.yaml", "taska": "o1_taskA", "label": "hibrida graph-LM (live LM, ml5120)"},
    "S1": {"cls": ROOT / "configs" / "ablation" / "seqgnn" / "S1_nine.yaml",             "taska": "s1_taskA", "label": "sekuensial (lmgat_seqgnn, ml1024 sama seperti graph)"},
}

# N48 templates -> (source path, output basename stem after the arch prefix)
# domain templates live in CFG/, cil templates in CIL/. cil_taskA_eval has no N48_ prefix.
TEMPLATES = [
    (CFG / "N48_taskA_importance_nine.yaml", CFG, "taskA_importance_nine"),
    (CFG / "N48_relearn_naive_nine.yaml",     CFG, "relearn_naive_nine"),
    (CFG / "N48_relearn_ewc_nine.yaml",       CFG, "relearn_ewc_nine"),
    (CFG / "N48_relearn_replay_nine.yaml",    CFG, "relearn_replay_nine"),
    (CFG / "N48_relearn_ewc_replay_nine.yaml",CFG, "relearn_ewc_replay_nine"),
    (CIL / "cil_taskA_eval_nine.yaml",        CIL, "cil_taskA_eval_nine"),
    (CIL / "N48_cil_naive_nine.yaml",         CIL, "cil_naive_nine"),
    (CIL / "N48_cil_ewc_nine.yaml",           CIL, "cil_ewc_nine"),
    (CIL / "N48_cil_replay_nine.yaml",        CIL, "cil_replay_nine"),
    (CIL / "N48_cil_ewc_replay_nine.yaml",    CIL, "cil_ewc_replay_nine"),
]


def _patch_paths(obj, old: str, new: str):
    """Recursively rename n48_taskA -> {arch}_taskA in ewc checkpoint paths."""
    if isinstance(obj, dict):
        return {k: _patch_paths(v, old, new) for k, v in obj.items()}
    if isinstance(obj, str):
        return obj.replace(old, new)
    return obj


def main() -> None:
    n = 0
    for prefix, meta in ARCHS.items():
        cls = yaml.safe_load(meta["cls"].read_text(encoding="utf-8"))
        arch_model, arch_train = cls["model"], cls["train"]
        for src, outdir, stem in TEMPLATES:
            cfg = yaml.safe_load(src.read_text(encoding="utf-8"))
            num_classes = cfg["model"]["num_classes"]        # 26 domain / 36 cil — keep the task's head size
            model = copy.deepcopy(arch_model)
            model["num_classes"] = num_classes
            cfg["model"] = model
            cfg["train"] = copy.deepcopy(arch_train)
            if "ewc" in cfg:
                cfg["ewc"] = _patch_paths(cfg["ewc"], "n48_taskA", meta["taska"])
            out = outdir / f"{prefix}_{stem}.yaml"
            header = (
                f"# GENERATED by scripts/gen_continual_arch_configs.py — DO NOT edit by hand.\n"
                f"# Continual config for the {meta['label']} architecture.\n"
                f"# model+train block from {meta['cls'].relative_to(ROOT).as_posix()}; "
                f"data/ewc/replay from {src.relative_to(ROOT).as_posix()}.\n"
            )
            out.write_text(header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False), encoding="utf-8")
            print("wrote", out.relative_to(ROOT).as_posix())
            n += 1
    print(f"\n{n} configs generated ({len(ARCHS)} archs x {len(TEMPLATES)} templates).")


if __name__ == "__main__":
    main()
